// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package demopackage

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	_ = "STUB: not implemented"
	return *new(DemoClient)
}

func (c *demoClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DemoServer is the server API for Demo service.
// All implementations must embed UnimplementedDemoServer
// for forward compatibility
type DemoServer interface {
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedDemoServer()
}

// UnimplementedDemoServer must be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (UnimplementedDemoServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedDemoServer) mustEmbedUnimplementedDemoServer() {
	_ = "STUB: not implemented"

	// UnsafeDemoServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to DemoServer will
	// result in compilation errors.
	return
}

type UnsafeDemoServer interface {
	mustEmbedUnimplementedDemoServer()
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) { _ = "STUB: not implemented"; return }

func _Demo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Demo_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http/server/proto/service.proto",
}
