// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_jwt is a generated GoMock package.
package mock_jwt

import (
	context "context"
	base64 "encoding/base64"

	jwt "github.com/go-masonry/mortar/interfaces/auth/jwt"
	gomock "github.com/golang/mock/gomock"
)

// MockExtractorBuilder is a mock of ExtractorBuilder interface.
type MockExtractorBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorBuilderMockRecorder
}

// MockExtractorBuilderMockRecorder is the mock recorder for MockExtractorBuilder.
type MockExtractorBuilderMockRecorder struct {
	mock *MockExtractorBuilder
}

// NewMockExtractorBuilder creates a new mock instance.
func NewMockExtractorBuilder(ctrl *gomock.Controller) *MockExtractorBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractorBuilder) EXPECT() *MockExtractorBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Build mocks base method.
	return nil
}

func (m *MockExtractorBuilder) Build() jwt.TokenExtractor {
	_ = "STUB: not implemented"
	return *new(jwt.TokenExtractor)
}

// Build indicates an expected call of Build.
func (mr *MockExtractorBuilderMockRecorder) Build() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetBase64Decoder mocks base method.
func (m *MockExtractorBuilder) SetBase64Decoder(dec *base64.Encoding) jwt.ExtractorBuilder {
	_ = "STUB: not implemented"
	return *new(jwt.ExtractorBuilder)
}

// SetBase64Decoder indicates an expected call of SetBase64Decoder.
func (mr *MockExtractorBuilderMockRecorder) SetBase64Decoder(dec interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetContextExtractor mocks base method.
func (m *MockExtractorBuilder) SetContextExtractor(extractor jwt.ContextExtractor) jwt.ExtractorBuilder {
	_ = "STUB: not implemented"
	return *new(jwt.ExtractorBuilder)
}

// SetContextExtractor indicates an expected call of SetContextExtractor.
func (mr *MockExtractorBuilderMockRecorder) SetContextExtractor(extractor interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDecoder mocks base method.
func (m *MockExtractorBuilder) SetDecoder(dec jwt.JSONDecoder) jwt.ExtractorBuilder {
	_ = "STUB: not implemented"
	return *new(jwt.ExtractorBuilder)
}

// SetDecoder indicates an expected call of SetDecoder.
func (mr *MockExtractorBuilderMockRecorder) SetDecoder(dec interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTokenExtractor is a mock of TokenExtractor interface.
type MockTokenExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockTokenExtractorMockRecorder
}

// MockTokenExtractorMockRecorder is the mock recorder for MockTokenExtractor.
type MockTokenExtractorMockRecorder struct {
	mock *MockTokenExtractor
}

// NewMockTokenExtractor creates a new mock instance.
func NewMockTokenExtractor(ctrl *gomock.Controller) *MockTokenExtractor {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenExtractor) EXPECT() *MockTokenExtractorMockRecorder {
	_ = "STUB: not implemented"

	// FromContext mocks base method.
	return nil
}

func (m *MockTokenExtractor) FromContext(ctx context.Context) (jwt.Token, error) {
	_ = "STUB: not implemented"
	return *new(jwt.Token), nil
}

// FromContext indicates an expected call of FromContext.
func (mr *MockTokenExtractorMockRecorder) FromContext(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FromString mocks base method.
func (m *MockTokenExtractor) FromString(str string) (jwt.Token, error) {
	_ = "STUB: not implemented"
	return *new(jwt.Token), nil
}

// FromString indicates an expected call of FromString.
func (mr *MockTokenExtractorMockRecorder) FromString(str interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	_ = "STUB: not implemented"

	// Decode mocks base method.
	return nil
}

func (m *MockToken) Decode(target interface{}) error { _ = "STUB: not implemented"; return nil }

// Decode indicates an expected call of Decode.
func (mr *MockTokenMockRecorder) Decode(target interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Map mocks base method.
func (m *MockToken) Map() (map[string]interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Map indicates an expected call of Map.
func (mr *MockTokenMockRecorder) Map() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Payload mocks base method.
func (m *MockToken) Payload() []byte { _ = "STUB: not implemented"; return nil }

// Payload indicates an expected call of Payload.
func (mr *MockTokenMockRecorder) Payload() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Raw mocks base method.
func (m *MockToken) Raw() string { _ = "STUB: not implemented"; return "" }

// Raw indicates an expected call of Raw.
func (mr *MockTokenMockRecorder) Raw() *gomock.Call { _ = "STUB: not implemented"; return nil }
