// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	http "net/http"

	client "github.com/go-masonry/mortar/interfaces/http/client"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockHTTPClientBuilder is a mock of HTTPClientBuilder interface.
type MockHTTPClientBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientBuilderMockRecorder
}

// MockHTTPClientBuilderMockRecorder is the mock recorder for MockHTTPClientBuilder.
type MockHTTPClientBuilderMockRecorder struct {
	mock *MockHTTPClientBuilder
}

// NewMockHTTPClientBuilder creates a new mock instance.
func NewMockHTTPClientBuilder(ctrl *gomock.Controller) *MockHTTPClientBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClientBuilder) EXPECT() *MockHTTPClientBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddInterceptors mocks base method.
	return nil
}

func (m *MockHTTPClientBuilder) AddInterceptors(arg0 ...client.HTTPClientInterceptor) client.HTTPClientBuilder {
	_ = "STUB: not implemented"
	return *new(client.HTTPClientBuilder)
}

// AddInterceptors indicates an expected call of AddInterceptors.
func (mr *MockHTTPClientBuilderMockRecorder) AddInterceptors(arg0 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Build mocks base method.
func (m *MockHTTPClientBuilder) Build() *http.Client { _ = "STUB: not implemented"; return nil }

// Build indicates an expected call of Build.
func (mr *MockHTTPClientBuilderMockRecorder) Build() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithPreconfiguredClient mocks base method.
func (m *MockHTTPClientBuilder) WithPreconfiguredClient(arg0 *http.Client) client.HTTPClientBuilder {
	_ = "STUB: not implemented"
	return *new(client.HTTPClientBuilder)
}

// WithPreconfiguredClient indicates an expected call of WithPreconfiguredClient.
func (mr *MockHTTPClientBuilderMockRecorder) WithPreconfiguredClient(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGRPCClientConnectionWrapper is a mock of GRPCClientConnectionWrapper interface.
type MockGRPCClientConnectionWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCClientConnectionWrapperMockRecorder
}

// MockGRPCClientConnectionWrapperMockRecorder is the mock recorder for MockGRPCClientConnectionWrapper.
type MockGRPCClientConnectionWrapperMockRecorder struct {
	mock *MockGRPCClientConnectionWrapper
}

// NewMockGRPCClientConnectionWrapper creates a new mock instance.
func NewMockGRPCClientConnectionWrapper(ctrl *gomock.Controller) *MockGRPCClientConnectionWrapper {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCClientConnectionWrapper) EXPECT() *MockGRPCClientConnectionWrapperMockRecorder {
	_ = "STUB: not implemented"

	// Dial mocks base method.
	return nil
}

func (m *MockGRPCClientConnectionWrapper) Dial(ctx context.Context, target string, extraOptions ...grpc.DialOption) (grpc.ClientConnInterface, error) {
	_ = "STUB: not implemented"
	return *new(grpc.ClientConnInterface), nil
}

// Dial indicates an expected call of Dial.
func (mr *MockGRPCClientConnectionWrapperMockRecorder) Dial(ctx, target interface{}, extraOptions ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGRPCClientConnectionBuilder is a mock of GRPCClientConnectionBuilder interface.
type MockGRPCClientConnectionBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCClientConnectionBuilderMockRecorder
}

// MockGRPCClientConnectionBuilderMockRecorder is the mock recorder for MockGRPCClientConnectionBuilder.
type MockGRPCClientConnectionBuilderMockRecorder struct {
	mock *MockGRPCClientConnectionBuilder
}

// NewMockGRPCClientConnectionBuilder creates a new mock instance.
func NewMockGRPCClientConnectionBuilder(ctrl *gomock.Controller) *MockGRPCClientConnectionBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCClientConnectionBuilder) EXPECT() *MockGRPCClientConnectionBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddOptions mocks base method.
	return nil
}

func (m *MockGRPCClientConnectionBuilder) AddOptions(opts ...grpc.DialOption) client.GRPCClientConnectionBuilder {
	_ = "STUB: not implemented"
	return *new(client.GRPCClientConnectionBuilder)
}

// AddOptions indicates an expected call of AddOptions.
func (mr *MockGRPCClientConnectionBuilderMockRecorder) AddOptions(opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Build mocks base method.
func (m *MockGRPCClientConnectionBuilder) Build() client.GRPCClientConnectionWrapper {
	_ = "STUB: not implemented"
	return *new(client.GRPCClientConnectionWrapper)
}

// Build indicates an expected call of Build.
func (mr *MockGRPCClientConnectionBuilderMockRecorder) Build() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
