// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_monitor is a generated GoMock package.
package mock_monitor

import (
	context "context"
	time "time"

	monitor "github.com/go-masonry/mortar/interfaces/monitor"
	gomock "github.com/golang/mock/gomock"
)

// MockTagsAwareCounter is a mock of TagsAwareCounter interface.
type MockTagsAwareCounter struct {
	ctrl     *gomock.Controller
	recorder *MockTagsAwareCounterMockRecorder
}

// MockTagsAwareCounterMockRecorder is the mock recorder for MockTagsAwareCounter.
type MockTagsAwareCounterMockRecorder struct {
	mock *MockTagsAwareCounter
}

// NewMockTagsAwareCounter creates a new mock instance.
func NewMockTagsAwareCounter(ctrl *gomock.Controller) *MockTagsAwareCounter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsAwareCounter) EXPECT() *MockTagsAwareCounterMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockTagsAwareCounter) Add(v float64) { _ = "STUB: not implemented"; return }

// Add indicates an expected call of Add.
func (mr *MockTagsAwareCounterMockRecorder) Add(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Inc mocks base method.
func (m *MockTagsAwareCounter) Inc() { _ = "STUB: not implemented"; return }

// Inc indicates an expected call of Inc.
func (mr *MockTagsAwareCounterMockRecorder) Inc() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithContext mocks base method.
func (m *MockTagsAwareCounter) WithContext(ctx context.Context) monitor.TagsAwareCounter {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareCounter)
}

// WithContext indicates an expected call of WithContext.
func (mr *MockTagsAwareCounterMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTags mocks base method.
func (m *MockTagsAwareCounter) WithTags(tags monitor.Tags) monitor.TagsAwareCounter {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareCounter)
}

// WithTags indicates an expected call of WithTags.
func (mr *MockTagsAwareCounterMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockCounter is a mock of Counter interface.
type MockCounter struct {
	ctrl     *gomock.Controller
	recorder *MockCounterMockRecorder
}

// MockCounterMockRecorder is the mock recorder for MockCounter.
type MockCounterMockRecorder struct {
	mock *MockCounter
}

// NewMockCounter creates a new mock instance.
func NewMockCounter(ctrl *gomock.Controller) *MockCounter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounter) EXPECT() *MockCounterMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockCounter) Add(v float64) { _ = "STUB: not implemented"; return }

// Add indicates an expected call of Add.
func (mr *MockCounterMockRecorder) Add(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Inc mocks base method.
func (m *MockCounter) Inc() { _ = "STUB: not implemented"; return }

// Inc indicates an expected call of Inc.
func (mr *MockCounterMockRecorder) Inc() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockTagsAwareGauge is a mock of TagsAwareGauge interface.
type MockTagsAwareGauge struct {
	ctrl     *gomock.Controller
	recorder *MockTagsAwareGaugeMockRecorder
}

// MockTagsAwareGaugeMockRecorder is the mock recorder for MockTagsAwareGauge.
type MockTagsAwareGaugeMockRecorder struct {
	mock *MockTagsAwareGauge
}

// NewMockTagsAwareGauge creates a new mock instance.
func NewMockTagsAwareGauge(ctrl *gomock.Controller) *MockTagsAwareGauge {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsAwareGauge) EXPECT() *MockTagsAwareGaugeMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockTagsAwareGauge) Add(v float64) { _ = "STUB: not implemented"; return }

// Add indicates an expected call of Add.
func (mr *MockTagsAwareGaugeMockRecorder) Add(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Dec mocks base method.
func (m *MockTagsAwareGauge) Dec() { _ = "STUB: not implemented"; return }

// Dec indicates an expected call of Dec.
func (mr *MockTagsAwareGaugeMockRecorder) Dec() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Inc mocks base method.
func (m *MockTagsAwareGauge) Inc() { _ = "STUB: not implemented"; return }

// Inc indicates an expected call of Inc.
func (mr *MockTagsAwareGaugeMockRecorder) Inc() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Set mocks base method.
func (m *MockTagsAwareGauge) Set(v float64) { _ = "STUB: not implemented"; return }

// Set indicates an expected call of Set.
func (mr *MockTagsAwareGaugeMockRecorder) Set(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithContext mocks base method.
func (m *MockTagsAwareGauge) WithContext(ctx context.Context) monitor.TagsAwareGauge {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareGauge)
}

// WithContext indicates an expected call of WithContext.
func (mr *MockTagsAwareGaugeMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTags mocks base method.
func (m *MockTagsAwareGauge) WithTags(tags monitor.Tags) monitor.TagsAwareGauge {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareGauge)
}

// WithTags indicates an expected call of WithTags.
func (mr *MockTagsAwareGaugeMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGauge is a mock of Gauge interface.
type MockGauge struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeMockRecorder
}

// MockGaugeMockRecorder is the mock recorder for MockGauge.
type MockGaugeMockRecorder struct {
	mock *MockGauge
}

// NewMockGauge creates a new mock instance.
func NewMockGauge(ctrl *gomock.Controller) *MockGauge { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGauge) EXPECT() *MockGaugeMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockGauge) Add(v float64) { _ = "STUB: not implemented"; return }

// Add indicates an expected call of Add.
func (mr *MockGaugeMockRecorder) Add(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Dec mocks base method.
func (m *MockGauge) Dec() { _ = "STUB: not implemented"; return }

// Dec indicates an expected call of Dec.
func (mr *MockGaugeMockRecorder) Dec() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Inc mocks base method.
func (m *MockGauge) Inc() { _ = "STUB: not implemented"; return }

// Inc indicates an expected call of Inc.
func (mr *MockGaugeMockRecorder) Inc() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Set mocks base method.
func (m *MockGauge) Set(v float64) { _ = "STUB: not implemented"; return }

// Set indicates an expected call of Set.
func (mr *MockGaugeMockRecorder) Set(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTagsAwareHistogram is a mock of TagsAwareHistogram interface.
type MockTagsAwareHistogram struct {
	ctrl     *gomock.Controller
	recorder *MockTagsAwareHistogramMockRecorder
}

// MockTagsAwareHistogramMockRecorder is the mock recorder for MockTagsAwareHistogram.
type MockTagsAwareHistogramMockRecorder struct {
	mock *MockTagsAwareHistogram
}

// NewMockTagsAwareHistogram creates a new mock instance.
func NewMockTagsAwareHistogram(ctrl *gomock.Controller) *MockTagsAwareHistogram {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsAwareHistogram) EXPECT() *MockTagsAwareHistogramMockRecorder {
	_ = "STUB: not implemented"

	// Record mocks base method.
	return nil
}

func (m *MockTagsAwareHistogram) Record(v float64) { _ = "STUB: not implemented"; return }

// Record indicates an expected call of Record.
func (mr *MockTagsAwareHistogramMockRecorder) Record(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithContext mocks base method.
func (m *MockTagsAwareHistogram) WithContext(ctx context.Context) monitor.TagsAwareHistogram {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareHistogram)
}

// WithContext indicates an expected call of WithContext.
func (mr *MockTagsAwareHistogramMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTags mocks base method.
func (m *MockTagsAwareHistogram) WithTags(tags monitor.Tags) monitor.TagsAwareHistogram {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareHistogram)
}

// WithTags indicates an expected call of WithTags.
func (mr *MockTagsAwareHistogramMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockHistogram is a mock of Histogram interface.
type MockHistogram struct {
	ctrl     *gomock.Controller
	recorder *MockHistogramMockRecorder
}

// MockHistogramMockRecorder is the mock recorder for MockHistogram.
type MockHistogramMockRecorder struct {
	mock *MockHistogram
}

// NewMockHistogram creates a new mock instance.
func NewMockHistogram(ctrl *gomock.Controller) *MockHistogram {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistogram) EXPECT() *MockHistogramMockRecorder {
	_ = "STUB: not implemented"

	// Record mocks base method.
	return nil
}

func (m *MockHistogram) Record(v float64) { _ = "STUB: not implemented"; return }

// Record indicates an expected call of Record.
func (mr *MockHistogramMockRecorder) Record(v interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTimer is a mock of Timer interface.
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTimerMockRecorder
}

// MockTimerMockRecorder is the mock recorder for MockTimer.
type MockTimerMockRecorder struct {
	mock *MockTimer
}

// NewMockTimer creates a new mock instance.
func NewMockTimer(ctrl *gomock.Controller) *MockTimer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimer) EXPECT() *MockTimerMockRecorder {
	_ = "STUB: not implemented"

	// Record mocks base method.
	return nil
}

func (m *MockTimer) Record(d time.Duration) { _ = "STUB: not implemented"; return }

// Record indicates an expected call of Record.
func (mr *MockTimerMockRecorder) Record(d interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTagsAwareTimer is a mock of TagsAwareTimer interface.
type MockTagsAwareTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTagsAwareTimerMockRecorder
}

// MockTagsAwareTimerMockRecorder is the mock recorder for MockTagsAwareTimer.
type MockTagsAwareTimerMockRecorder struct {
	mock *MockTagsAwareTimer
}

// NewMockTagsAwareTimer creates a new mock instance.
func NewMockTagsAwareTimer(ctrl *gomock.Controller) *MockTagsAwareTimer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsAwareTimer) EXPECT() *MockTagsAwareTimerMockRecorder {
	_ = "STUB: not implemented"

	// Record mocks base method.
	return nil
}

func (m *MockTagsAwareTimer) Record(d time.Duration) { _ = "STUB: not implemented"; return }

// Record indicates an expected call of Record.
func (mr *MockTagsAwareTimerMockRecorder) Record(d interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithContext mocks base method.
func (m *MockTagsAwareTimer) WithContext(ctx context.Context) monitor.TagsAwareTimer {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareTimer)
}

// WithContext indicates an expected call of WithContext.
func (mr *MockTagsAwareTimerMockRecorder) WithContext(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTags mocks base method.
func (m *MockTagsAwareTimer) WithTags(tags monitor.Tags) monitor.TagsAwareTimer {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareTimer)
}

// WithTags indicates an expected call of WithTags.
func (mr *MockTagsAwareTimerMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	_ = "STUB: not implemented"

	// Counter mocks base method.
	return nil
}

func (m *MockMetrics) Counter(name, desc string) monitor.TagsAwareCounter {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareCounter)
}

// Counter indicates an expected call of Counter.
func (mr *MockMetricsMockRecorder) Counter(name, desc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Gauge mocks base method.
func (m *MockMetrics) Gauge(name, desc string) monitor.TagsAwareGauge {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareGauge)
}

// Gauge indicates an expected call of Gauge.
func (mr *MockMetricsMockRecorder) Gauge(name, desc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Histogram mocks base method.
func (m *MockMetrics) Histogram(name, desc string, buckets monitor.Buckets) monitor.TagsAwareHistogram {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareHistogram)
}

// Histogram indicates an expected call of Histogram.
func (mr *MockMetricsMockRecorder) Histogram(name, desc, buckets interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Timer mocks base method.
func (m *MockMetrics) Timer(name, desc string) monitor.TagsAwareTimer {
	_ = "STUB: not implemented"
	return *new(monitor.TagsAwareTimer)
}

// Timer indicates an expected call of Timer.
func (mr *MockMetricsMockRecorder) Timer(name, desc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithTags mocks base method.
func (m *MockMetrics) WithTags(tags monitor.Tags) monitor.Metrics {
	_ = "STUB: not implemented"
	return *new(monitor.Metrics)
}

// WithTags indicates an expected call of WithTags.
func (mr *MockMetricsMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockReporter) Close(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockReporterMockRecorder) Close(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connect mocks base method.
func (m *MockReporter) Connect(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Connect indicates an expected call of Connect.
func (mr *MockReporterMockRecorder) Connect(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Metrics mocks base method.
func (m *MockReporter) Metrics() monitor.Metrics {
	_ = "STUB: not implemented"
	return *new(monitor.Metrics)
}

// Metrics indicates an expected call of Metrics.
func (mr *MockReporterMockRecorder) Metrics() *gomock.Call { _ = "STUB: not implemented"; return nil }
