// Code generated by MockGen. DO NOT EDIT.
// Source: bricks.go

// Package mock_monitor is a generated GoMock package.
package mock_monitor

import (
	context "context"

	monitor "github.com/go-masonry/mortar/interfaces/monitor"
	gomock "github.com/golang/mock/gomock"
)

// MockBrickMetric is a mock of BrickMetric interface.
type MockBrickMetric struct {
	ctrl     *gomock.Controller
	recorder *MockBrickMetricMockRecorder
}

// MockBrickMetricMockRecorder is the mock recorder for MockBrickMetric.
type MockBrickMetricMockRecorder struct {
	mock *MockBrickMetric
}

// NewMockBrickMetric creates a new mock instance.
func NewMockBrickMetric(ctrl *gomock.Controller) *MockBrickMetric {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrickMetric) EXPECT() *MockBrickMetricMockRecorder {
	_ = "STUB: not implemented"

	// MockBricksCounter is a mock of BricksCounter interface.
	return nil
}

type MockBricksCounter struct {
	ctrl     *gomock.Controller
	recorder *MockBricksCounterMockRecorder
}

// MockBricksCounterMockRecorder is the mock recorder for MockBricksCounter.
type MockBricksCounterMockRecorder struct {
	mock *MockBricksCounter
}

// NewMockBricksCounter creates a new mock instance.
func NewMockBricksCounter(ctrl *gomock.Controller) *MockBricksCounter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksCounter) EXPECT() *MockBricksCounterMockRecorder {
	_ = "STUB: not implemented"

	// WithTags mocks base method.
	return nil
}

func (m *MockBricksCounter) WithTags(tags map[string]string) (monitor.Counter, error) {
	_ = "STUB: not implemented"
	return *new(monitor.Counter), nil
}

// WithTags indicates an expected call of WithTags.
func (mr *MockBricksCounterMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBricksGauge is a mock of BricksGauge interface.
type MockBricksGauge struct {
	ctrl     *gomock.Controller
	recorder *MockBricksGaugeMockRecorder
}

// MockBricksGaugeMockRecorder is the mock recorder for MockBricksGauge.
type MockBricksGaugeMockRecorder struct {
	mock *MockBricksGauge
}

// NewMockBricksGauge creates a new mock instance.
func NewMockBricksGauge(ctrl *gomock.Controller) *MockBricksGauge {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksGauge) EXPECT() *MockBricksGaugeMockRecorder {
	_ = "STUB: not implemented"

	// WithTags mocks base method.
	return nil
}

func (m *MockBricksGauge) WithTags(tags map[string]string) (monitor.Gauge, error) {
	_ = "STUB: not implemented"
	return *new(monitor.Gauge), nil
}

// WithTags indicates an expected call of WithTags.
func (mr *MockBricksGaugeMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBricksHistogram is a mock of BricksHistogram interface.
type MockBricksHistogram struct {
	ctrl     *gomock.Controller
	recorder *MockBricksHistogramMockRecorder
}

// MockBricksHistogramMockRecorder is the mock recorder for MockBricksHistogram.
type MockBricksHistogramMockRecorder struct {
	mock *MockBricksHistogram
}

// NewMockBricksHistogram creates a new mock instance.
func NewMockBricksHistogram(ctrl *gomock.Controller) *MockBricksHistogram {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksHistogram) EXPECT() *MockBricksHistogramMockRecorder {
	_ = "STUB: not implemented"

	// WithTags mocks base method.
	return nil
}

func (m *MockBricksHistogram) WithTags(tags map[string]string) (monitor.Histogram, error) {
	_ = "STUB: not implemented"
	return *new(monitor.Histogram), nil
}

// WithTags indicates an expected call of WithTags.
func (mr *MockBricksHistogramMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBricksTimer is a mock of BricksTimer interface.
type MockBricksTimer struct {
	ctrl     *gomock.Controller
	recorder *MockBricksTimerMockRecorder
}

// MockBricksTimerMockRecorder is the mock recorder for MockBricksTimer.
type MockBricksTimerMockRecorder struct {
	mock *MockBricksTimer
}

// NewMockBricksTimer creates a new mock instance.
func NewMockBricksTimer(ctrl *gomock.Controller) *MockBricksTimer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksTimer) EXPECT() *MockBricksTimerMockRecorder {
	_ = "STUB: not implemented"

	// WithTags mocks base method.
	return nil
}

func (m *MockBricksTimer) WithTags(tags map[string]string) (monitor.Timer, error) {
	_ = "STUB: not implemented"
	return *new(monitor.Timer), nil
}

// WithTags indicates an expected call of WithTags.
func (mr *MockBricksTimerMockRecorder) WithTags(tags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBricksMetrics is a mock of BricksMetrics interface.
type MockBricksMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockBricksMetricsMockRecorder
}

// MockBricksMetricsMockRecorder is the mock recorder for MockBricksMetrics.
type MockBricksMetricsMockRecorder struct {
	mock *MockBricksMetrics
}

// NewMockBricksMetrics creates a new mock instance.
func NewMockBricksMetrics(ctrl *gomock.Controller) *MockBricksMetrics {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksMetrics) EXPECT() *MockBricksMetricsMockRecorder {
	_ = "STUB: not implemented"

	// Counter mocks base method.
	return nil
}

func (m *MockBricksMetrics) Counter(name, desc string, tagKeys ...string) (monitor.BricksCounter, error) {
	_ = "STUB: not implemented"
	return *new(monitor.BricksCounter), nil
}

// Counter indicates an expected call of Counter.
func (mr *MockBricksMetricsMockRecorder) Counter(name, desc interface{}, tagKeys ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Gauge mocks base method.
func (m *MockBricksMetrics) Gauge(name, desc string, tagKeys ...string) (monitor.BricksGauge, error) {
	_ = "STUB: not implemented"
	return *new(monitor.BricksGauge), nil
}

// Gauge indicates an expected call of Gauge.
func (mr *MockBricksMetricsMockRecorder) Gauge(name, desc interface{}, tagKeys ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Histogram mocks base method.
func (m *MockBricksMetrics) Histogram(name, desc string, buckets []float64, tagKeys ...string) (monitor.BricksHistogram, error) {
	_ = "STUB: not implemented"
	return *new(monitor.BricksHistogram), nil
}

// Histogram indicates an expected call of Histogram.
func (mr *MockBricksMetricsMockRecorder) Histogram(name, desc, buckets interface{}, tagKeys ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Remove mocks base method.
func (m *MockBricksMetrics) Remove(metric monitor.BrickMetric) error {
	_ = "STUB: not implemented"
	return nil
}

// Remove indicates an expected call of Remove.
func (mr *MockBricksMetricsMockRecorder) Remove(metric interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Timer mocks base method.
func (m *MockBricksMetrics) Timer(name, desc string, tagKeys ...string) (monitor.BricksTimer, error) {
	_ = "STUB: not implemented"
	return *new(monitor.BricksTimer), nil
}

// Timer indicates an expected call of Timer.
func (mr *MockBricksMetricsMockRecorder) Timer(name, desc interface{}, tagKeys ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBricksReporter is a mock of BricksReporter interface.
type MockBricksReporter struct {
	ctrl     *gomock.Controller
	recorder *MockBricksReporterMockRecorder
}

// MockBricksReporterMockRecorder is the mock recorder for MockBricksReporter.
type MockBricksReporterMockRecorder struct {
	mock *MockBricksReporter
}

// NewMockBricksReporter creates a new mock instance.
func NewMockBricksReporter(ctrl *gomock.Controller) *MockBricksReporter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBricksReporter) EXPECT() *MockBricksReporterMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockBricksReporter) Close(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Close indicates an expected call of Close.
func (mr *MockBricksReporterMockRecorder) Close(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connect mocks base method.
func (m *MockBricksReporter) Connect(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Connect indicates an expected call of Connect.
func (mr *MockBricksReporterMockRecorder) Connect(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Metrics mocks base method.
func (m *MockBricksReporter) Metrics() monitor.BricksMetrics {
	_ = "STUB: not implemented"
	return *new(monitor.BricksMetrics)
}

// Metrics indicates an expected call of Metrics.
func (mr *MockBricksReporterMockRecorder) Metrics() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Build mocks base method.
	return nil
}

func (m *MockBuilder) Build() monitor.BricksReporter {
	_ = "STUB: not implemented"
	return *new(monitor.BricksReporter)
}

// Build indicates an expected call of Build.
func (mr *MockBuilderMockRecorder) Build() *gomock.Call { _ = "STUB: not implemented"; return nil }
