// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_log is a generated GoMock package.
package mock_log

import (
	context "context"

	log "github.com/go-masonry/mortar/interfaces/log"
	gomock "github.com/golang/mock/gomock"
)

// MockLoggerConfiguration is a mock of LoggerConfiguration interface.
type MockLoggerConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerConfigurationMockRecorder
}

// MockLoggerConfigurationMockRecorder is the mock recorder for MockLoggerConfiguration.
type MockLoggerConfigurationMockRecorder struct {
	mock *MockLoggerConfiguration
}

// NewMockLoggerConfiguration creates a new mock instance.
func NewMockLoggerConfiguration(ctrl *gomock.Controller) *MockLoggerConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerConfiguration) EXPECT() *MockLoggerConfigurationMockRecorder {
	_ = "STUB: not implemented"

	// Implementation mocks base method.
	return nil
}

func (m *MockLoggerConfiguration) Implementation() interface{} {
	_ = "STUB: not implemented"
	return nil
}

// Implementation indicates an expected call of Implementation.
func (mr *MockLoggerConfigurationMockRecorder) Implementation() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Level mocks base method.
func (m *MockLoggerConfiguration) Level() log.Level {
	_ = "STUB: not implemented"
	return *new(log.Level)
}

// Level indicates an expected call of Level.
func (mr *MockLoggerConfigurationMockRecorder) Level() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	_ = "STUB: not implemented"

	// Build mocks base method.
	return nil
}

func (m *MockBuilder) Build() log.Logger { _ = "STUB: not implemented"; return *new(log.Logger) }

// Build indicates an expected call of Build.
func (mr *MockBuilderMockRecorder) Build() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IncrementSkipFrames mocks base method.
func (m *MockBuilder) IncrementSkipFrames(addition int) log.Builder {
	_ = "STUB: not implemented"
	return *new(log.Builder)
}

// IncrementSkipFrames indicates an expected call of IncrementSkipFrames.
func (mr *MockBuilderMockRecorder) IncrementSkipFrames(addition interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetLevel mocks base method.
func (m *MockBuilder) SetLevel(level log.Level) log.Builder {
	_ = "STUB: not implemented"
	return *new(log.Builder)
}

// SetLevel indicates an expected call of SetLevel.
func (mr *MockBuilderMockRecorder) SetLevel(level interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMessages is a mock of Messages interface.
type MockMessages struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesMockRecorder
}

// MockMessagesMockRecorder is the mock recorder for MockMessages.
type MockMessagesMockRecorder struct {
	mock *MockMessages
}

// NewMockMessages creates a new mock instance.
func NewMockMessages(ctrl *gomock.Controller) *MockMessages { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessages) EXPECT() *MockMessagesMockRecorder {
	_ = "STUB: not implemented"

	// Custom mocks base method.
	return nil
}

func (m *MockMessages) Custom(ctx context.Context, level log.Level, skipAdditionalFrames int, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Custom indicates an expected call of Custom.
func (mr *MockMessagesMockRecorder) Custom(ctx, level, skipAdditionalFrames, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Debug mocks base method.
func (m *MockMessages) Debug(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Debug indicates an expected call of Debug.
func (mr *MockMessagesMockRecorder) Debug(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Error mocks base method.
func (m *MockMessages) Error(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Error indicates an expected call of Error.
func (mr *MockMessagesMockRecorder) Error(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockMessages) Info(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Info indicates an expected call of Info.
func (mr *MockMessagesMockRecorder) Info(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trace mocks base method.
func (m *MockMessages) Trace(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Trace indicates an expected call of Trace.
func (mr *MockMessagesMockRecorder) Trace(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Warn mocks base method.
func (m *MockMessages) Warn(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Warn indicates an expected call of Warn.
func (mr *MockMessagesMockRecorder) Warn(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockFields is a mock of Fields interface.
type MockFields struct {
	ctrl     *gomock.Controller
	recorder *MockFieldsMockRecorder
}

// MockFieldsMockRecorder is the mock recorder for MockFields.
type MockFieldsMockRecorder struct {
	mock *MockFields
}

// NewMockFields creates a new mock instance.
func NewMockFields(ctrl *gomock.Controller) *MockFields { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFields) EXPECT() *MockFieldsMockRecorder {
	_ = "STUB: not implemented"

	// Custom mocks base method.
	return nil
}

func (m *MockFields) Custom(ctx context.Context, level log.Level, skipAdditionalFrames int, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Custom indicates an expected call of Custom.
func (mr *MockFieldsMockRecorder) Custom(ctx, level, skipAdditionalFrames, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Debug mocks base method.
func (m *MockFields) Debug(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Debug indicates an expected call of Debug.
func (mr *MockFieldsMockRecorder) Debug(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Error mocks base method.
func (m *MockFields) Error(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Error indicates an expected call of Error.
func (mr *MockFieldsMockRecorder) Error(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockFields) Info(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Info indicates an expected call of Info.
func (mr *MockFieldsMockRecorder) Info(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trace mocks base method.
func (m *MockFields) Trace(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Trace indicates an expected call of Trace.
func (mr *MockFieldsMockRecorder) Trace(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Warn mocks base method.
func (m *MockFields) Warn(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Warn indicates an expected call of Warn.
func (mr *MockFieldsMockRecorder) Warn(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithError mocks base method.
func (m *MockFields) WithError(err error) log.Fields {
	_ = "STUB: not implemented"
	return *new(log.Fields)
}

// WithError indicates an expected call of WithError.
func (mr *MockFieldsMockRecorder) WithError(err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithField mocks base method.
func (m *MockFields) WithField(name string, value interface{}) log.Fields {
	_ = "STUB: not implemented"
	return *new(log.Fields)
}

// WithField indicates an expected call of WithField.
func (mr *MockFieldsMockRecorder) WithField(name, value interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	_ = "STUB: not implemented"

	// Configuration mocks base method.
	return nil
}

func (m *MockLogger) Configuration() log.LoggerConfiguration {
	_ = "STUB: not implemented"
	return *new(log.LoggerConfiguration)
}

// Configuration indicates an expected call of Configuration.
func (mr *MockLoggerMockRecorder) Configuration() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Custom mocks base method.
func (m *MockLogger) Custom(ctx context.Context, level log.Level, skipAdditionalFrames int, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Custom indicates an expected call of Custom.
func (mr *MockLoggerMockRecorder) Custom(ctx, level, skipAdditionalFrames, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Debug mocks base method.
func (m *MockLogger) Debug(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockLogger) Info(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trace mocks base method.
func (m *MockLogger) Trace(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Trace indicates an expected call of Trace.
func (mr *MockLoggerMockRecorder) Trace(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Warn mocks base method.
func (m *MockLogger) Warn(ctx context.Context, format string, args ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(ctx, format interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithError mocks base method.
func (m *MockLogger) WithError(err error) log.Fields {
	_ = "STUB: not implemented"
	return *new(log.Fields)
}

// WithError indicates an expected call of WithError.
func (mr *MockLoggerMockRecorder) WithError(err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithField mocks base method.
func (m *MockLogger) WithField(name string, value interface{}) log.Fields {
	_ = "STUB: not implemented"
	return *new(log.Fields)
}

// WithField indicates an expected call of WithField.
func (mr *MockLoggerMockRecorder) WithField(name, value interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
