// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_server is a generated GoMock package.
package mock_server

import (
	context "context"
	net "net"
	http "net/http"

	server "github.com/go-masonry/mortar/interfaces/http/server"
	gomock "github.com/golang/mock/gomock"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// MockWebService is a mock of WebService interface.
type MockWebService struct {
	ctrl     *gomock.Controller
	recorder *MockWebServiceMockRecorder
}

// MockWebServiceMockRecorder is the mock recorder for MockWebService.
type MockWebServiceMockRecorder struct {
	mock *MockWebService
}

// NewMockWebService creates a new mock instance.
func NewMockWebService(ctrl *gomock.Controller) *MockWebService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebService) EXPECT() *MockWebServiceMockRecorder {
	_ = "STUB: not implemented"

	// Ports mocks base method.
	return nil
}

func (m *MockWebService) Ports() []server.ListenInfo { _ = "STUB: not implemented"; return nil }

// Ports indicates an expected call of Ports.
func (mr *MockWebServiceMockRecorder) Ports() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Run mocks base method.
func (m *MockWebService) Run(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Run indicates an expected call of Run.
func (mr *MockWebServiceMockRecorder) Run(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockWebService) Stop(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Stop indicates an expected call of Stop.
func (mr *MockWebServiceMockRecorder) Stop(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGRPCWebServiceBuilder is a mock of GRPCWebServiceBuilder interface.
type MockGRPCWebServiceBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCWebServiceBuilderMockRecorder
}

// MockGRPCWebServiceBuilderMockRecorder is the mock recorder for MockGRPCWebServiceBuilder.
type MockGRPCWebServiceBuilderMockRecorder struct {
	mock *MockGRPCWebServiceBuilder
}

// NewMockGRPCWebServiceBuilder creates a new mock instance.
func NewMockGRPCWebServiceBuilder(ctrl *gomock.Controller) *MockGRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCWebServiceBuilder) EXPECT() *MockGRPCWebServiceBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddGRPCServerOptions mocks base method.
	return nil
}

func (m *MockGRPCWebServiceBuilder) AddGRPCServerOptions(options ...grpc.ServerOption) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// AddGRPCServerOptions indicates an expected call of AddGRPCServerOptions.
func (mr *MockGRPCWebServiceBuilderMockRecorder) AddGRPCServerOptions(options ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddRESTServerConfiguration mocks base method.
func (m *MockGRPCWebServiceBuilder) AddRESTServerConfiguration() server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// AddRESTServerConfiguration indicates an expected call of AddRESTServerConfiguration.
func (mr *MockGRPCWebServiceBuilderMockRecorder) AddRESTServerConfiguration() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Build mocks base method.
func (m *MockGRPCWebServiceBuilder) Build() (server.WebService, error) {
	_ = "STUB: not implemented"
	return *new(server.WebService), nil
}

// Build indicates an expected call of Build.
func (mr *MockGRPCWebServiceBuilderMockRecorder) Build() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListenOn mocks base method.
func (m *MockGRPCWebServiceBuilder) ListenOn(addr string) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// ListenOn indicates an expected call of ListenOn.
func (mr *MockGRPCWebServiceBuilderMockRecorder) ListenOn(addr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterGRPCAPIs mocks base method.
func (m *MockGRPCWebServiceBuilder) RegisterGRPCAPIs(register ...server.GRPCServerAPI) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// RegisterGRPCAPIs indicates an expected call of RegisterGRPCAPIs.
func (mr *MockGRPCWebServiceBuilderMockRecorder) RegisterGRPCAPIs(register ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomGRPCServer mocks base method.
func (m *MockGRPCWebServiceBuilder) SetCustomGRPCServer(customServer *grpc.Server) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// SetCustomGRPCServer indicates an expected call of SetCustomGRPCServer.
func (mr *MockGRPCWebServiceBuilderMockRecorder) SetCustomGRPCServer(customServer interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomListener mocks base method.
func (m *MockGRPCWebServiceBuilder) SetCustomListener(listener net.Listener) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// SetCustomListener indicates an expected call of SetCustomListener.
func (mr *MockGRPCWebServiceBuilderMockRecorder) SetCustomListener(listener interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetLogger mocks base method.
func (m *MockGRPCWebServiceBuilder) SetLogger(logger func(context.Context, string, ...interface{})) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockGRPCWebServiceBuilderMockRecorder) SetLogger(logger interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetPanicHandler mocks base method.
func (m *MockGRPCWebServiceBuilder) SetPanicHandler(handler func(interface{}) error) server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// SetPanicHandler indicates an expected call of SetPanicHandler.
func (mr *MockGRPCWebServiceBuilderMockRecorder) SetPanicHandler(handler interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRESTBuilder is a mock of RESTBuilder interface.
type MockRESTBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockRESTBuilderMockRecorder
}

// MockRESTBuilderMockRecorder is the mock recorder for MockRESTBuilder.
type MockRESTBuilderMockRecorder struct {
	mock *MockRESTBuilder
}

// NewMockRESTBuilder creates a new mock instance.
func NewMockRESTBuilder(ctrl *gomock.Controller) *MockRESTBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRESTBuilder) EXPECT() *MockRESTBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddGRPCGatewayInterceptors mocks base method.
	return nil
}

func (m *MockRESTBuilder) AddGRPCGatewayInterceptors(interceptors ...server.GRPCGatewayInterceptor) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// AddGRPCGatewayInterceptors indicates an expected call of AddGRPCGatewayInterceptors.
func (mr *MockRESTBuilderMockRecorder) AddGRPCGatewayInterceptors(interceptors ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddGRPCGatewayOptions mocks base method.
func (m *MockRESTBuilder) AddGRPCGatewayOptions(options ...runtime.ServeMuxOption) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// AddGRPCGatewayOptions indicates an expected call of AddGRPCGatewayOptions.
func (mr *MockRESTBuilderMockRecorder) AddGRPCGatewayOptions(options ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddHandler mocks base method.
func (m *MockRESTBuilder) AddHandler(pattern string, handler http.Handler) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockRESTBuilderMockRecorder) AddHandler(pattern, handler interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddHandlerFunc mocks base method.
func (m *MockRESTBuilder) AddHandlerFunc(pattern string, handlerFunc http.HandlerFunc) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// AddHandlerFunc indicates an expected call of AddHandlerFunc.
func (mr *MockRESTBuilderMockRecorder) AddHandlerFunc(pattern, handlerFunc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BuildRESTPart mocks base method.
func (m *MockRESTBuilder) BuildRESTPart() server.GRPCWebServiceBuilder {
	_ = "STUB: not implemented"
	return *new(server.GRPCWebServiceBuilder)
}

// BuildRESTPart indicates an expected call of BuildRESTPart.
func (mr *MockRESTBuilderMockRecorder) BuildRESTPart() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListenOn mocks base method.
func (m *MockRESTBuilder) ListenOn(addr string) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// ListenOn indicates an expected call of ListenOn.
func (mr *MockRESTBuilderMockRecorder) ListenOn(addr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterGRPCGatewayHandlers mocks base method.
func (m *MockRESTBuilder) RegisterGRPCGatewayHandlers(handlers ...server.GRPCGatewayGeneratedHandlers) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// RegisterGRPCGatewayHandlers indicates an expected call of RegisterGRPCGatewayHandlers.
func (mr *MockRESTBuilderMockRecorder) RegisterGRPCGatewayHandlers(handlers ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomGRPCGatewayMux mocks base method.
func (m *MockRESTBuilder) SetCustomGRPCGatewayMux(mux *runtime.ServeMux) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// SetCustomGRPCGatewayMux indicates an expected call of SetCustomGRPCGatewayMux.
func (mr *MockRESTBuilderMockRecorder) SetCustomGRPCGatewayMux(mux interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomListener mocks base method.
func (m *MockRESTBuilder) SetCustomListener(listener net.Listener) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// SetCustomListener indicates an expected call of SetCustomListener.
func (mr *MockRESTBuilderMockRecorder) SetCustomListener(listener interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomServer mocks base method.
func (m *MockRESTBuilder) SetCustomServer(customServer *http.Server) server.RESTBuilder {
	_ = "STUB: not implemented"
	return *new(server.RESTBuilder)
}

// SetCustomServer indicates an expected call of SetCustomServer.
func (mr *MockRESTBuilderMockRecorder) SetCustomServer(customServer interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
