// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_trace is a generated GoMock package.
package mock_trace

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	opentracing "github.com/opentracing/opentracing-go"
)

// MockOpenTracer is a mock of OpenTracer interface.
type MockOpenTracer struct {
	ctrl     *gomock.Controller
	recorder *MockOpenTracerMockRecorder
}

// MockOpenTracerMockRecorder is the mock recorder for MockOpenTracer.
type MockOpenTracerMockRecorder struct {
	mock *MockOpenTracer
}

// NewMockOpenTracer creates a new mock instance.
func NewMockOpenTracer(ctrl *gomock.Controller) *MockOpenTracer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenTracer) EXPECT() *MockOpenTracerMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockOpenTracer) Close(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockOpenTracerMockRecorder) Close(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connect mocks base method.
func (m *MockOpenTracer) Connect(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Connect indicates an expected call of Connect.
func (mr *MockOpenTracerMockRecorder) Connect(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Tracer mocks base method.
func (m *MockOpenTracer) Tracer() opentracing.Tracer {
	_ = "STUB: not implemented"
	return *new(opentracing.Tracer)
}

// Tracer indicates an expected call of Tracer.
func (mr *MockOpenTracerMockRecorder) Tracer() *gomock.Call { _ = "STUB: not implemented"; return nil }
