// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_cfg is a generated GoMock package.
package mock_cfg

import (
	time "time"

	cfg "github.com/go-masonry/mortar/interfaces/cfg"
	gomock "github.com/golang/mock/gomock"
)

// MockValue is a mock of Value interface.
type MockValue struct {
	ctrl     *gomock.Controller
	recorder *MockValueMockRecorder
}

// MockValueMockRecorder is the mock recorder for MockValue.
type MockValueMockRecorder struct {
	mock *MockValue
}

// NewMockValue creates a new mock instance.
func NewMockValue(ctrl *gomock.Controller) *MockValue { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValue) EXPECT() *MockValueMockRecorder {
	_ = "STUB: not implemented"

	// Bool mocks base method.
	return nil
}

func (m *MockValue) Bool() bool { _ = "STUB: not implemented"; return false }

// Bool indicates an expected call of Bool.
func (mr *MockValueMockRecorder) Bool() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Duration mocks base method.
func (m *MockValue) Duration() time.Duration { _ = "STUB: not implemented"; return *new(time.Duration) }

// Duration indicates an expected call of Duration.
func (mr *MockValueMockRecorder) Duration() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Float64 mocks base method.
func (m *MockValue) Float64() float64 { _ = "STUB: not implemented"; return 0 }

// Float64 indicates an expected call of Float64.
func (mr *MockValueMockRecorder) Float64() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Int mocks base method.
func (m *MockValue) Int() int { _ = "STUB: not implemented"; return 0 }

// Int indicates an expected call of Int.
func (mr *MockValueMockRecorder) Int() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Int32 mocks base method.
func (m *MockValue) Int32() int32 { _ = "STUB: not implemented"; return 0 }

// Int32 indicates an expected call of Int32.
func (mr *MockValueMockRecorder) Int32() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Int64 mocks base method.
func (m *MockValue) Int64() int64 { _ = "STUB: not implemented"; return 0 }

// Int64 indicates an expected call of Int64.
func (mr *MockValueMockRecorder) Int64() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IntSlice mocks base method.
func (m *MockValue) IntSlice() []int { _ = "STUB: not implemented"; return nil }

// IntSlice indicates an expected call of IntSlice.
func (mr *MockValueMockRecorder) IntSlice() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsSet mocks base method.
func (m *MockValue) IsSet() bool { _ = "STUB: not implemented"; return false }

// IsSet indicates an expected call of IsSet.
func (mr *MockValueMockRecorder) IsSet() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Raw mocks base method.
func (m *MockValue) Raw() interface{} { _ = "STUB: not implemented"; return nil }

// Raw indicates an expected call of Raw.
func (mr *MockValueMockRecorder) Raw() *gomock.Call { _ = "STUB: not implemented"; return nil }

// String mocks base method.
func (m *MockValue) String() string { _ = "STUB: not implemented"; return "" }

// String indicates an expected call of String.
func (mr *MockValueMockRecorder) String() *gomock.Call { _ = "STUB: not implemented"; return nil }

// StringMap mocks base method.
func (m *MockValue) StringMap() map[string]interface{} { _ = "STUB: not implemented"; return nil }

// StringMap indicates an expected call of StringMap.
func (mr *MockValueMockRecorder) StringMap() *gomock.Call { _ = "STUB: not implemented"; return nil }

// StringMapString mocks base method.
func (m *MockValue) StringMapString() map[string]string { _ = "STUB: not implemented"; return nil }

// StringMapString indicates an expected call of StringMapString.
func (mr *MockValueMockRecorder) StringMapString() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StringMapStringSlice mocks base method.
func (m *MockValue) StringMapStringSlice() map[string][]string {
	_ = "STUB: not implemented"
	return nil
}

// StringMapStringSlice indicates an expected call of StringMapStringSlice.
func (mr *MockValueMockRecorder) StringMapStringSlice() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StringSlice mocks base method.
func (m *MockValue) StringSlice() []string { _ = "STUB: not implemented"; return nil }

// StringSlice indicates an expected call of StringSlice.
func (mr *MockValueMockRecorder) StringSlice() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Time mocks base method.
func (m *MockValue) Time() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Time indicates an expected call of Time.
func (mr *MockValueMockRecorder) Time() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Uint mocks base method.
func (m *MockValue) Uint() uint { _ = "STUB: not implemented"; return 0 }

// Uint indicates an expected call of Uint.
func (mr *MockValueMockRecorder) Uint() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Uint32 mocks base method.
func (m *MockValue) Uint32() uint32 { _ = "STUB: not implemented"; return 0 }

// Uint32 indicates an expected call of Uint32.
func (mr *MockValueMockRecorder) Uint32() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Uint64 mocks base method.
func (m *MockValue) Uint64() uint64 { _ = "STUB: not implemented"; return 0 }

// Uint64 indicates an expected call of Uint64.
func (mr *MockValueMockRecorder) Uint64() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Unmarshal mocks base method.
func (m *MockValue) Unmarshal(result interface{}) error { _ = "STUB: not implemented"; return nil }

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockValueMockRecorder) Unmarshal(result interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockConfig) Get(key string) cfg.Value { _ = "STUB: not implemented"; return *new(cfg.Value) }

// Get indicates an expected call of Get.
func (mr *MockConfigMockRecorder) Get(key interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Implementation mocks base method.
func (m *MockConfig) Implementation() interface{} { _ = "STUB: not implemented"; return nil }

// Implementation indicates an expected call of Implementation.
func (mr *MockConfigMockRecorder) Implementation() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Map mocks base method.
func (m *MockConfig) Map() map[string]interface{} { _ = "STUB: not implemented"; return nil }

// Map indicates an expected call of Map.
func (mr *MockConfigMockRecorder) Map() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Set mocks base method.
func (m *MockConfig) Set(key string, value interface{}) { _ = "STUB: not implemented"; return }

// Set indicates an expected call of Set.
func (mr *MockConfigMockRecorder) Set(key, value interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	_ = "STUB: not implemented"

	// AddExtraConfigFile mocks base method.
	return nil
}

func (m *MockBuilder) AddExtraConfigFile(path string) cfg.Builder {
	_ = "STUB: not implemented"
	return *new(cfg.Builder)
}

// AddExtraConfigFile indicates an expected call of AddExtraConfigFile.
func (mr *MockBuilderMockRecorder) AddExtraConfigFile(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Build mocks base method.
func (m *MockBuilder) Build() (cfg.Config, error) {
	_ = "STUB: not implemented"
	return *new(cfg.Config), nil
}

// Build indicates an expected call of Build.
func (mr *MockBuilderMockRecorder) Build() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetConfigFile mocks base method.
func (m *MockBuilder) SetConfigFile(path string) cfg.Builder {
	_ = "STUB: not implemented"
	return *new(cfg.Builder)
}

// SetConfigFile indicates an expected call of SetConfigFile.
func (mr *MockBuilderMockRecorder) SetConfigFile(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetEnvDelimiterReplacer mocks base method.
func (m *MockBuilder) SetEnvDelimiterReplacer(from, to string) cfg.Builder {
	_ = "STUB: not implemented"
	return *new(cfg.Builder)
}

// SetEnvDelimiterReplacer indicates an expected call of SetEnvDelimiterReplacer.
func (mr *MockBuilderMockRecorder) SetEnvDelimiterReplacer(from, to interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
